version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          node-version: 16.18.0
      - aws-cli/setup
      - eb/setup
      - checkout
      # starting installing server dependencies ...
      - run:
          name: Install server dependencies
          command: npm run install:server
      # building back-end side ...
      - run:
          name: Build server
          command: npm run build:server
      # building front-end side ...
      - run:
          name: Build website
          command: npm run build:website
      # deploying back-end side to elastic beanstalk
      - run:
          name: Deploy server to eb
          command: npm run deploy:server
      # deploying front-end side to bucket s3
      - run:
          name: Deploy website to s3
          command: npm run deploy:website

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main